# Generated by Django 3.0.4 on 2020-03-25 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='name')),
                ('director', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='worstFilms/images')),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(default='')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('rate', models.IntegerField(choices=[(-1, 'One'), (-2, 'Two'), (-3, 'Three'), (-4, 'Four'), (-5, 'Five')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
