# Generated by Django 3.0.4 on 2020-04-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_relation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ['-created_date']},
        ),
    ]
